server:
  error:
    whitelabel:
      enabled: false
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs.yaml
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
  cache:
    disabled: true
